<?php
function stoica_init_acf_sections_fields() {
    if( function_exists('acf_add_local_field_group') ):

        acf_add_local_field_group(array(
            'key' => 'group_5ffd63bd98576',
            'title' => 'Website Sections',
            'fields' => array(
                array(
                    'key' => 'field_5ffd63d58c0d4',
                    'label' => 'Sections',
                    'name' => 'sections',
                    'type' => 'flexible_content',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layouts' => array(
                        'layout_5ffd63dfd8761' => array(
                            'key' => 'layout_5ffd63dfd8761',
                            'name' => 'homehero-content',
                            'label' => 'Home Banner Section',
                            'display' => 'table',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_5ffd64551ff1d',
                                    'label' => 'Banner Text Left',
                                    'name' => 'hero_text_left',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_5ffd645c1ff1e',
                                    'label' => 'Banner Right Image',
                                    'name' => 'hero_right_image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'medium',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                                array(
                                    'key' => 'field_5ffd788be534f',
                                    'label' => 'Left Button',
                                    'name' => 'left_button',
                                    'type' => 'link',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                ),
                                array(
                                    'key' => 'field_5ffd7878e534e',
                                    'label' => 'Right Button',
                                    'name' => 'right_button',
                                    'type' => 'link',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_5ffd66869265a' => array(
                            'key' => 'layout_5ffd66869265a',
                            'name' => 'our_services_page_content',
                            'label' => 'Our Services Page Section',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_5ffd65b3e0248',
                                    'label' => 'Section Background Color',
                                    'name' => 'services_basckground_color',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                ),
                                array(
                                    'key' => 'field_5ffd669d9265b',
                                    'label' => 'Our Services left Text',
                                    'name' => 'our_services_left_text',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_5ffd66b99265c',
                                    'label' => 'Our Services Right List',
                                    'name' => 'our_services_right_list',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'collapsed' => '',
                                    'min' => 0,
                                    'max' => 0,
                                    'layout' => 'block',
                                    'button_label' => '',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_5ffd66df1f594',
                                            'label' => 'Icon',
                                            'name' => 'icon',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'return_format' => 'array',
                                            'preview_size' => 'medium',
                                            'library' => 'all',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                        ),
                                        array(
                                            'key' => 'field_5ffd66ea1f595',
                                            'label' => 'Service Text',
                                            'name' => 'service_text',
                                            'type' => 'wysiwyg',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'tabs' => 'all',
                                            'toolbar' => 'full',
                                            'media_upload' => 1,
                                            'delay' => 0,
                                        ),
                                    ),
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_5ffd762a4fadd' => array(
                            'key' => 'layout_5ffd762a4fadd',
                            'name' => 'whatyouget_content',
                            'label' => 'What You Get Page Section',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_5ffd779857510',
                                    'label' => 'Section Background Color',
                                    'name' => 'background_color',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                ),
                                array(
                                    'key' => 'field_5ffd76434fade',
                                    'label' => 'Section Title',
                                    'name' => 'section_title',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_5ffd765a4fadf',
                                    'label' => 'You Get List',
                                    'name' => 'you_get_list',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'collapsed' => '',
                                    'min' => 0,
                                    'max' => 0,
                                    'layout' => 'table',
                                    'button_label' => '',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_5ffd7685c0f97',
                                            'label' => 'Left Icon',
                                            'name' => 'left_icon',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'return_format' => 'array',
                                            'preview_size' => 'medium',
                                            'library' => 'all',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                        ),
                                        array(
                                            'key' => 'field_5ffd7695c0f98',
                                            'label' => 'You Get Text',
                                            'name' => 'you_get_text',
                                            'type' => 'wysiwyg',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'tabs' => 'all',
                                            'toolbar' => 'full',
                                            'media_upload' => 1,
                                            'delay' => 0,
                                        ),
                                    ),
                                ),
                                array(
                                    'key' => 'field_5ffd76b8dbb27',
                                    'label' => 'Right Image',
                                    'name' => 'right_image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'medium',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_5ffd76e6461ae' => array(
                            'key' => 'layout_5ffd76e6461ae',
                            'name' => 'homeportfolio-content',
                            'label' => 'Portfolio Page Listing Section',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_5ffd770a461af',
                                    'label' => 'Portfolio Items',
                                    'name' => 'portfolio_items',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'collapsed' => '',
                                    'min' => 0,
                                    'max' => 0,
                                    'layout' => 'table',
                                    'button_label' => 'Add Item',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_5ffd78050e300',
                                            'label' => 'Portfolio Link',
                                            'name' => 'portfolio_link',
                                            'type' => 'link',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'return_format' => 'array',
                                        ),
                                        array(
                                            'key' => 'field_5ffd78200e301',
                                            'label' => 'Portfolio Image',
                                            'name' => 'portfolio_image',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'return_format' => 'array',
                                            'preview_size' => 'medium',
                                            'library' => 'all',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                        ),
                                    ),
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_5ffd7861e534d' => array(
                            'key' => 'layout_5ffd7861e534d',
                            'name' => 'our_clients_content',
                            'label' => 'Our clients Section',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_5ffd78aa15787',
                                    'label' => 'Section Background Color',
                                    'name' => 'section_background_color',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                ),
                                array(
                                    'key' => 'field_5ffd78c415788',
                                    'label' => 'Our Clients Left Text',
                                    'name' => 'our_clients_left_text',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_5ffd78d115789',
                                    'label' => 'Our Clients Button',
                                    'name' => 'our_clients_button',
                                    'type' => 'link',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                ),
                                array(
                                    'key' => 'field_5ffd78e91578a',
                                    'label' => 'Our Clients Listing',
                                    'name' => 'our_clients_listing',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'collapsed' => '',
                                    'min' => 0,
                                    'max' => 0,
                                    'layout' => 'table',
                                    'button_label' => '',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_5ffd78fa1578b',
                                            'label' => 'Client Logo',
                                            'name' => 'client_logo_img',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'return_format' => 'array',
                                            'preview_size' => 'medium',
                                            'library' => 'all',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                        ),
                                        array(
                                            'key' => 'field_5ffd79061578c',
                                            'label' => 'Client Link',
                                            'name' => 'client_link',
                                            'type' => 'link',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'return_format' => 'array',
                                        ),
                                    ),
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_5ffd79b1cb090' => array(
                            'key' => 'layout_5ffd79b1cb090',
                            'name' => 'clients_testimonials_content',
                            'label' => 'Clients testimonials Section',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_5ffd7b5f34127',
                                    'label' => 'Section Background Color',
                                    'name' => 'section_background_color',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                ),
                                array(
                                    'key' => 'field_5ffd79c5cb091',
                                    'label' => 'Left Text',
                                    'name' => 'left_text',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_5ffd79def00b2',
                                    'label' => 'Testimonials Carousel',
                                    'name' => 'testimonials_carousel',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'collapsed' => '',
                                    'min' => 0,
                                    'max' => 0,
                                    'layout' => 'table',
                                    'button_label' => '',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_5ffd7a04f6bf7',
                                            'label' => 'Testimonial Icon',
                                            'name' => 'testimonial_icon',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'return_format' => 'array',
                                            'preview_size' => 'medium',
                                            'library' => 'all',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                        ),
                                        array(
                                            'key' => 'field_5ffd7a1df6bf8',
                                            'label' => 'Client Name',
                                            'name' => 'client_name',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                        array(
                                            'key' => 'field_5ffd7a29f6bf9',
                                            'label' => 'Client Role',
                                            'name' => 'client_role',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                        array(
                                            'key' => 'field_5ffd7a31f6bfa',
                                            'label' => 'Testimonial Message',
                                            'name' => 'testimonial_message',
                                            'type' => 'textarea',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'maxlength' => '',
                                            'rows' => '',
                                            'new_lines' => '',
                                        ),
                                    ),
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_5ffd7b88bcee4' => array(
                            'key' => 'layout_5ffd7b88bcee4',
                            'name' => 'schedule_consultation_content',
                            'label' => 'Schedule consultation Section',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_5ffd7babbcee5',
                                    'label' => 'Left Column',
                                    'name' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'left',
                                    'endpoint' => 0,
                                ),
                                array(
                                    'key' => 'field_5ffd7c3f9426e',
                                    'label' => 'Left Column Background Color',
                                    'name' => 'left_column_background_color',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                ),
                                array(
                                    'key' => 'field_5ffd7bc9bcee6',
                                    'label' => 'Left Column Text',
                                    'name' => 'left_column_text',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_5ffd7be1bcee7',
                                    'label' => 'Left Column Image',
                                    'name' => 'left_column_image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'medium',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                                array(
                                    'key' => 'field_5ffd7bf6bcee8',
                                    'label' => 'Right Column',
                                    'name' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'left',
                                    'endpoint' => 0,
                                ),
                                array(
                                    'key' => 'field_5ffd7c609426f',
                                    'label' => 'Right Column Background Color',
                                    'name' => 'right_column_background_color',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                ),
                                array(
                                    'key' => 'field_5ffd7c0ebcee9',
                                    'label' => 'Right Column Text',
                                    'name' => 'right_column_text',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_5ffd7c1dbceea',
                                    'label' => 'Right Column Image',
                                    'name' => 'right_column_image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'medium',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_5ffd7ca12ec74' => array(
                            'key' => 'layout_5ffd7ca12ec74',
                            'name' => 'latest_stories_content',
                            'label' => 'Latest stories Section',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_5ffd7cb72ec75',
                                    'label' => 'Latest stories title',
                                    'name' => 'latest_stories_title',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_5ffd7cdd2ec76',
                                    'label' => 'Background Color',
                                    'name' => 'background_color',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_600c8c2450ef8' => array(
                            'key' => 'layout_600c8c2450ef8',
                            'name' => 'page_simple_banner_content',
                            'label' => 'Page Simple Banner Section',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_600c8c8b50efc',
                                    'label' => 'Banner Content',
                                    'name' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'left',
                                    'endpoint' => 0,
                                ),
                                array(
                                    'key' => 'field_600c8c6350efa',
                                    'label' => 'Banner Background Color',
                                    'name' => 'banner_background_color',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                ),
                                array(
                                    'key' => 'field_600c8c4650ef9',
                                    'label' => 'Banner Text Content',
                                    'name' => 'banner_content',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_600c8cae50efd',
                                    'label' => 'Banner Buttons',
                                    'name' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'top',
                                    'endpoint' => 0,
                                ),
                                array(
                                    'key' => 'field_600c8cc606b1a',
                                    'label' => 'Show Buttons?',
                                    'name' => 'show_buttons',
                                    'type' => 'checkbox',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'yes' => 'Yes',
                                    ),
                                    'allow_custom' => 0,
                                    'default_value' => array(
                                    ),
                                    'layout' => 'vertical',
                                    'toggle' => 0,
                                    'return_format' => 'value',
                                    'save_custom' => 0,
                                ),
                                array(
                                    'key' => 'field_600c8ce406b1b',
                                    'label' => 'Button 1',
                                    'name' => 'button_1',
                                    'type' => 'link',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_600c8cc606b1a',
                                                'operator' => '==',
                                                'value' => 'yes',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                ),
                                array(
                                    'key' => 'field_600c8ced06b1c',
                                    'label' => 'Button 2',
                                    'name' => 'button_2',
                                    'type' => 'link',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_600c8cc606b1a',
                                                'operator' => '==',
                                                'value' => 'yes',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_600c8d2eaec0c' => array(
                            'key' => 'layout_600c8d2eaec0c',
                            'name' => 'page_intro_content',
                            'label' => 'Page Intro Section',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_600c8d38aec0d',
                                    'label' => 'Content Section',
                                    'name' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'left',
                                    'endpoint' => 0,
                                ),
                                array(
                                    'key' => 'field_600c8d72aec0e',
                                    'label' => 'Text Content',
                                    'name' => 'text_content',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_600c8d81aec0f',
                                    'label' => 'Image and Backgound Section',
                                    'name' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'left',
                                    'endpoint' => 0,
                                ),
                                array(
                                    'key' => 'field_600c8da9aec10',
                                    'label' => 'Background Color',
                                    'name' => 'background_color',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                ),
                                array(
                                    'key' => 'field_600c8dceaec11',
                                    'label' => 'Right Image',
                                    'name' => 'right_image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'medium',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_600c8fffac25f' => array(
                            'key' => 'layout_600c8fffac25f',
                            'name' => 'team_listing_content',
                            'label' => 'Our Team Section',
                            'display' => 'row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_600c9013ac260',
                                    'label' => 'Section Title',
                                    'name' => 'section_title',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_600c9028ac261',
                                    'label' => 'Members Listing',
                                    'name' => 'members_listing',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'collapsed' => '',
                                    'min' => 0,
                                    'max' => 0,
                                    'layout' => 'table',
                                    'button_label' => 'Add Member',
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_600c904d3349e',
                                            'label' => 'Member Image',
                                            'name' => 'member_image',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'return_format' => 'array',
                                            'preview_size' => 'medium',
                                            'library' => 'all',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '',
                                        ),
                                        array(
                                            'key' => 'field_600c905c3349f',
                                            'label' => 'Member Name',
                                            'name' => 'member_name',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                        array(
                                            'key' => 'field_600c9083334a0',
                                            'label' => 'Member Role',
                                            'name' => 'member_role',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                    ),
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_600c90f040d3b' => array(
                            'key' => 'layout_600c90f040d3b',
                            'name' => 'page_contact_content',
                            'label' => 'Page Contact Section',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_600c93d16a6b0',
                                    'label' => 'Background Color',
                                    'name' => 'background_color',
                                    'type' => 'color_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                ),
                                array(
                                    'key' => 'field_600c914140d3c',
                                    'label' => 'Right Text Content',
                                    'name' => 'right_text_content',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_600c915a40d3d',
                                    'label' => 'Form Shortcode',
                                    'name' => 'form_shortcode',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                    ),
                    'button_label' => 'Add Section',
                    'min' => '',
                    'max' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'template-ribbons.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));

    endif;
}
add_action('acf/init', 'stoica_init_acf_sections_fields');
